import React, { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { SlidersHorizontal, X } from 'lucide-react'
import api from '../services/axiosInstance'
import ProductCard from '../components/product/ProductCard'

const initial = { category: [], brand: [], gender: [], size: [], color: [], rating: '', discount: false, availability: false, minPrice: '', maxPrice: '' }
const title = s => s.replace(/[-_]/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
function FilterPanel({ filters, setFilters, options, clear }) {
  const toggle = (key, value) => setFilters(f => ({ ...f, [key]: f[key].includes(value) ? f[key].filter(v => v !== value) : [...f[key], value] }))
  const group = (key, label) => options[key]?.length ? <div className="border-t border-atelier-lightgray/50 pt-4"><p className="font-mono text-xs uppercase tracking-widest mb-2">{label}</p>{options[key].map(value => <label key={value} className="block py-1.5 text-sm"><input type="checkbox" checked={filters[key].includes(value)} onChange={() => toggle(key, value)} className="mr-2"/>{title(value)}</label>)}</div> : null
  return <div className="space-y-4"><div className="flex justify-between"><b className="font-serif text-lg">Filters</b><button onClick={clear} className="font-mono text-xs uppercase underline">Clear all</button></div><div className="border-t border-atelier-lightgray/50 pt-4"><p className="font-mono text-xs uppercase tracking-widest mb-2">Price range</p><div className="flex gap-2"><input type="number" value={filters.minPrice} onChange={e => setFilters(f => ({...f,minPrice:e.target.value}))} placeholder="Min" className="w-1/2 border p-2 bg-transparent"/><input type="number" value={filters.maxPrice} onChange={e => setFilters(f => ({...f,maxPrice:e.target.value}))} placeholder="Max" className="w-1/2 border p-2 bg-transparent"/></div></div>{group('category','Category')}{group('brand','Brand')}{group('gender','Gender')}{group('size','Size')}{group('color','Color')}<div className="border-t border-atelier-lightgray/50 pt-4"><p className="font-mono text-xs uppercase tracking-widest mb-2">Rating</p>{[4,3,2].map(n => <label key={n} className="block py-1"><input type="radio" name="rating" checked={filters.rating === String(n)} onChange={() => setFilters(f => ({...f,rating:String(n)}))} className="mr-2"/>{n}+ stars</label>)}</div><label className="block border-t border-atelier-lightgray/50 pt-4"><input type="checkbox" checked={filters.discount} onChange={e => setFilters(f => ({...f,discount:e.target.checked}))} className="mr-2"/>On sale</label><label className="block"><input type="checkbox" checked={filters.availability} onChange={e => setFilters(f => ({...f,availability:e.target.checked}))} className="mr-2"/>In stock</label></div>
}
export default function Shop() {
  const [params, setParams] = useSearchParams(); const [products, setProducts] = useState([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [filters, setFilters] = useState(initial); const [sort, setSort] = useState('newest'); const [mobile, setMobile] = useState(false); const [page, setPage] = useState(1)
  const query = params.get('q') || ''
  const options = useMemo(() => ({ category:[...new Set(products.map(p=>p.category).filter(Boolean))], brand:[...new Set(products.map(p=>p.brand).filter(Boolean))], gender:[...new Set(products.map(p=>p.gender).filter(Boolean))], size:[...new Set(products.flatMap(p=>p.sizes||[]))], color:[...new Set(products.flatMap(p=>p.colors||[]))] }), [products])
  useEffect(() => { const load = async () => { setLoading(true); try { const sp = new URLSearchParams({ page, limit:24, sort }); if(query) sp.set('q',query); Object.entries(filters).forEach(([k,v]) => { if(Array.isArray(v) && v.length) sp.set(k,v.join(',')); else if(v && k !== 'discount' && k !== 'availability') sp.set(k,v); else if(v && k === 'discount') sp.set(k,'true'); else if(v && k === 'availability') sp.set(k,'in-stock') }); const {data}=await api.get(`products?${sp}`); setProducts(data.products||[]); setTotal(data.totalProducts||0) } finally {setLoading(false)} }; load() }, [query, filters, sort, page])
  const clear = () => { setFilters(initial); setPage(1) }; const chips = Object.entries(filters).flatMap(([k,v]) => Array.isArray(v) ? v.map(x=>[k,x]) : v ? [[k,v]] : [])
  return <div className="max-w-7xl mx-auto px-4 py-10"><div className="flex flex-wrap justify-between gap-4 border-b pb-6 mb-5"><div><p className="font-mono text-xs uppercase tracking-widest text-atelier-gray">Catalogue</p><h1 className="font-serif text-3xl">{query ? `Search: “${query}”` : 'All products'}</h1></div><div className="flex gap-2"><button onClick={()=>setMobile(true)} className="lg:hidden border px-3"><SlidersHorizontal size={16}/></button><select value={sort} onChange={e=>setSort(e.target.value)} className="border px-3 bg-transparent"><option value="newest">Newest</option><option value="lowToHigh">Price: Low to High</option><option value="highToLow">Price: High to Low</option><option value="popularity">Popularity</option><option value="bestSelling">Best Selling</option><option value="highestRated">Highest Rated</option></select></div></div>{chips.length>0&&<div className="flex flex-wrap gap-2 mb-5">{chips.map(([k,v])=><button key={`${k}-${v}`} onClick={()=>Array.isArray(filters[k])?setFilters(f=>({...f,[k]:f[k].filter(x=>x!==v)})):setFilters(f=>({...f,[k]:k==='discount'||k==='availability'?false:''}))} className="border px-2 py-1 text-xs">{title(String(v))} ×</button>)}<button onClick={clear} className="text-xs underline">Clear all</button></div>}<div className="grid lg:grid-cols-4 gap-8"><aside className="hidden lg:block"><FilterPanel filters={filters} setFilters={setFilters} options={options} clear={clear}/></aside><main className="lg:col-span-3"><p className="mb-5 text-sm text-atelier-gray">{total} products</p>{loading?<p>Loading products…</p>:products.length?<div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">{products.map(p=><ProductCard key={p._id} product={{...p,id:p._id,price:p.discountPrice||p.price,originalPrice:p.discountPrice?p.price:null,images:(p.images||[]).map(i=>i.url||i),colors:(p.colors||[]).map(name=>({name,hex:'#888'}))}}/>)}</div>:<p className="font-serif text-xl text-atelier-gray">No products match these filters.</p>}{products.length===24&&<button onClick={()=>setPage(p=>p+1)} className="btn-atelier-outline mt-10">Load more</button>}</main></div>{mobile&&<div className="fixed inset-0 z-50 bg-black/40 lg:hidden"><aside className="absolute bottom-0 w-full max-h-[85vh] overflow-auto bg-atelier-beige p-6 rounded-t-2xl"><button onClick={()=>setMobile(false)} className="float-right"><X/></button><FilterPanel filters={filters} setFilters={setFilters} options={options} clear={clear}/><button onClick={()=>setMobile(false)} className="btn-atelier-dark w-full mt-5">View results</button></aside></div>}</div>
}
